"""aura/tools/doc_generator.py — Documentation generator tool.

Generates structured Markdown documentation for code projects, APIs, or any
topic from a structured description.  Outputs are saved to
``~/.aura/docs/<name>.md``.

Usage
-----
    /tool doc_generator help
    /tool doc_generator create name="MyAPI" type=api \\
        title="My REST API" description="A weather data API" \\
        author="Jane Smith" version="1.0.0"
    /tool doc_generator create name="MyLib" type=library \\
        title="mylib" description="Python utility library" \\
        install="pip install mylib"
    /tool doc_generator list
    /tool doc_generator show MyAPI

Document types
--------------
  api       — REST API reference with endpoints table, authentication, errors
  library   — Python/JS library with install, quickstart, API reference
  readme    — Standard GitHub README with badges, features, and contributing
  guide     — Tutorial / how-to guide with numbered steps
"""

from __future__ import annotations

import re
import shlex
from datetime import date
from pathlib import Path
from typing import Dict

from .registry import Tool

_DOCS_DIR = Path.home() / ".aura" / "docs"

# ── Document templates ─────────────────────────────────────────────────────────

_API_TEMPLATE = """\
# {title}

> {description}

**Version:** {version}  **Author:** {author}  **Date:** {today}

---

## Table of Contents
1. [Overview](#overview)
2. [Authentication](#authentication)
3. [Endpoints](#endpoints)
4. [Error Codes](#error-codes)
5. [Examples](#examples)

---

## Overview

{description}

**Base URL:** `https://api.example.com/v1`

---

## Authentication

This API uses Bearer token authentication.  Include your API key in the
`Authorization` header:

```http
Authorization: Bearer YOUR_API_KEY
```

---

## Endpoints

| Method | Path | Description |
|--------|------|-------------|
| `GET`  | `/health` | Health check — returns `200 OK` if the API is up |
| `GET`  | `/resource` | List all resources |
| `POST` | `/resource` | Create a new resource |
| `GET`  | `/resource/{{id}}` | Get a resource by ID |
| `PUT`  | `/resource/{{id}}` | Update a resource |
| `DELETE` | `/resource/{{id}}` | Delete a resource |

### GET /resource

Returns a paginated list of resources.

**Query parameters:**

| Parameter | Type | Default | Description |
|-----------|------|---------|-------------|
| `page`    | int  | 1       | Page number |
| `limit`   | int  | 20      | Results per page (max 100) |

**Response:**

```json
{{
  "data": [],
  "total": 0,
  "page": 1,
  "limit": 20
}}
```

---

## Error Codes

| Code | Meaning |
|------|---------|
| 400  | Bad Request — check your request body |
| 401  | Unauthorised — invalid or missing API key |
| 404  | Not Found |
| 429  | Rate Limited — slow down your requests |
| 500  | Internal Server Error |

---

## Examples

### cURL

```bash
curl -H "Authorization: Bearer YOUR_KEY" \\
     https://api.example.com/v1/resource
```

### Python

```python
import requests

resp = requests.get(
    "https://api.example.com/v1/resource",
    headers={{"Authorization": "Bearer YOUR_KEY"}},
)
data = resp.json()
```

---

*Generated by AURA — {today}*
"""

_LIBRARY_TEMPLATE = """\
# {title}

> {description}

[![License](https://img.shields.io/badge/License-MIT-blue.svg)](LICENSE)

**Version:** {version}  **Author:** {author}

---

## Installation

```bash
{install}
```

---

## Quick Start

```python
import {module_name}

# Basic usage
result = {module_name}.do_something()
print(result)
```

---

## API Reference

### `{module_name}.do_something(param: str) -> str`

Does something useful.

**Parameters:**
- `param` — the input string

**Returns:** A processed string.

**Example:**
```python
from {module_name} import do_something
print(do_something("hello"))  # "HELLO"
```

---

## Configuration

| Setting | Default | Description |
|---------|---------|-------------|
| `DEBUG` | `False` | Enable verbose logging |
| `TIMEOUT` | `30` | Request timeout in seconds |

---

## Contributing

1. Fork the repository
2. Create a feature branch (`git checkout -b feature/amazing-feature`)
3. Commit your changes (`git commit -m 'Add amazing feature'`)
4. Push to the branch (`git push origin feature/amazing-feature`)
5. Open a Pull Request

---

## License

MIT — see [LICENSE](LICENSE) for details.

*Generated by AURA — {today}*
"""

_README_TEMPLATE = """\
# {title}

> {description}

[![License](https://img.shields.io/badge/License-Apache_2.0-blue.svg)](LICENSE)

---

## ✦ Features

- ✅ Feature one — describe a key capability
- ✅ Feature two — describe another capability
- ✅ Feature three — describe a third capability
- 🔜 Coming soon — roadmap item

---

## ✦ Getting Started

### Prerequisites

- Python 3.9+ (or Node.js 18+)

### Installation

```bash
{install}
```

### Usage

```bash
# Start the application
{usage}
```

---

## ✦ Documentation

See the [docs/](docs/) directory for detailed documentation.

---

## ✦ Contributing

Contributions are welcome!  Please read [CONTRIBUTING.md](CONTRIBUTING.md)
for guidelines.

---

## ✦ License

Apache 2.0 — see [LICENSE](LICENSE).

**Author:** {author}

*Generated by AURA — {today}*
"""

_GUIDE_TEMPLATE = """\
# {title}

> {description}

**Author:** {author}  **Last updated:** {today}

---

## Overview

This guide walks you through {description_lower}.

By the end you will be able to:
- Complete step 1 successfully
- Understand the core concepts
- Apply this knowledge to your own projects

---

## Prerequisites

Before you begin, make sure you have:
- [ ] Prerequisite 1 (e.g., Python 3.9+ installed)
- [ ] Prerequisite 2 (e.g., an API key from the service)
- [ ] Basic familiarity with the command line

---

## Step 1 — Set Up Your Environment

Start by creating a project directory and a virtual environment:

```bash
mkdir my-project && cd my-project
python -m venv venv
source venv/bin/activate   # Windows: venv\\Scripts\\activate
```

---

## Step 2 — Install Dependencies

Install the required packages:

```bash
pip install -r requirements.txt
```

---

## Step 3 — Configure the Application

Copy the example configuration file and fill in your details:

```bash
cp config.example.yaml config.yaml
# Edit config.yaml with your preferred text editor
```

---

## Step 4 — Run the Application

Start the application and verify it works:

```bash
python main.py
# Expected output: "Application started on http://localhost:8000"
```

---

## Troubleshooting

**Problem:** `ModuleNotFoundError`
**Solution:** Make sure your virtual environment is activated and dependencies are installed.

**Problem:** `Permission denied`
**Solution:** Check file permissions with `ls -la` and ensure you own the files.

---

## Next Steps

- Explore the [full documentation](docs/)
- Check out the [examples](examples/) directory
- Join the community on [GitHub Discussions](../../discussions)

---

*Generated by AURA — {today}*
"""


def _parse_kv(args: str) -> Dict[str, str]:
    result: Dict[str, str] = {}
    try:
        tokens = shlex.split(args)
    except ValueError:
        tokens = args.split()
    for token in tokens:
        if "=" in token:
            k, _, v = token.partition("=")
            result[k.strip().lower()] = v.strip().strip('"').strip("'")
    return result


class DocGeneratorTool(Tool):
    """Generate structured Markdown documentation for any project or API."""

    name = "doc_generator"
    description = (
        "Generate Markdown documentation.  "
        "Usage: /tool doc_generator create name=\"MyAPI\" type=api "
        "title=\"Title\" description=\"Description\" author=\"Name\""
    )

    def run(self, args: str) -> str:
        parts = args.strip().split(None, 1)
        if not parts or parts[0].lower() in ("help", ""):
            return self._help()

        subcmd = parts[0].lower()
        rest = parts[1] if len(parts) > 1 else ""

        if subcmd == "create":
            return self._create(rest)
        if subcmd == "list":
            return self._list()
        if subcmd == "show":
            return self._show(rest.strip())
        return self._help()

    # ── private ────────────────────────────────────────────────────────────────

    def _create(self, args: str) -> str:
        kv = _parse_kv(args)
        name = kv.get("name", "MyDoc")
        doc_type = kv.get("type", "readme").lower()
        title = kv.get("title", name)
        description = kv.get("description", "A well-documented project.")
        author = kv.get("author", "AURA User")
        version = kv.get("version", "1.0.0")
        install = kv.get("install", f"pip install {name.lower()}")
        usage = kv.get("usage", f"python -m {name.lower()}")
        today_str = date.today().isoformat()
        module_name = re.sub(r"[^\w]", "_", name.lower())

        template_map = {
            "api": _API_TEMPLATE,
            "library": _LIBRARY_TEMPLATE,
            "readme": _README_TEMPLATE,
            "guide": _GUIDE_TEMPLATE,
        }
        template = template_map.get(doc_type, _README_TEMPLATE)

        content = template.format(
            title=title,
            description=description,
            description_lower=description.lower(),
            author=author,
            version=version,
            install=install,
            usage=usage,
            today=today_str,
            module_name=module_name,
        )

        _DOCS_DIR.mkdir(parents=True, exist_ok=True)
        safe = re.sub(r"[^\w-]", "_", name)
        path = _DOCS_DIR / f"{safe}.md"
        path.write_text(content, encoding="utf-8")

        return (
            f"📖 **Documentation '{name}' generated!** (type: {doc_type})\n\n"
            f"Saved to: `{path}`\n\n"
            "---\n\n"
            f"{content}"
        )

    def _list(self) -> str:
        _DOCS_DIR.mkdir(parents=True, exist_ok=True)
        files = sorted(_DOCS_DIR.glob("*.md"))
        if not files:
            return "📂 No docs generated yet.  Use `/tool doc_generator create ...`"
        lines = ["📚 Generated docs:"]
        for f in files:
            lines.append(f"  • {f.name}")
        return "\n".join(lines)

    def _show(self, name: str) -> str:
        if not name:
            return "⚠️  Usage: /tool doc_generator show <name>"
        _DOCS_DIR.mkdir(parents=True, exist_ok=True)
        path = _DOCS_DIR / name
        if not path.exists():
            path = _DOCS_DIR / f"{name}.md"
        if not path.exists():
            return f"⚠️  Doc '{name}' not found.  Use 'list' to see available docs."
        return path.read_text(encoding="utf-8")

    @staticmethod
    def _help() -> str:
        return (
            "📖 **Doc Generator** — generate Markdown documentation.\n\n"
            "  **API docs:**\n"
            "  `/tool doc_generator create name=\"MyAPI\" type=api "
            "title=\"My API\" description=\"A REST API\"`\n\n"
            "  **Library docs:**\n"
            "  `/tool doc_generator create name=\"mylib\" type=library "
            "title=\"mylib\" install=\"pip install mylib\"`\n\n"
            "  **README:**\n"
            "  `/tool doc_generator create name=\"MyApp\" type=readme "
            "title=\"MyApp\" description=\"An awesome app\"`\n\n"
            "  **Tutorial guide:**\n"
            "  `/tool doc_generator create name=\"SetupGuide\" type=guide "
            "title=\"Setup Guide\" description=\"setting up the project\"`\n\n"
            "  **List:** `/tool doc_generator list`  "
            "**Show:** `/tool doc_generator show <name>`\n\n"
            "  **Types:** `api`, `library`, `readme`, `guide`"
        )
