"""aura/tools/resume_builder.py — Professional resume generator.

Generates a clean, plain-text or Markdown resume from a structured prompt.
The user provides their information and AURA formats it into a professional
document ready to paste into a word processor or share as-is.

Usage
-----
    /tool resume_builder help
    /tool resume_builder create name="Jane Smith" role="Software Engineer" \\
        skills="Python,Go,Docker" experience="5 years at Acme Corp" \\
        education="BSc Computer Science, MIT" email="jane@example.com"

Output: A Markdown-formatted resume saved to ~/.aura/resumes/<name>.md
and printed to the chat.
"""

from __future__ import annotations

import re
import shlex
from pathlib import Path
from typing import Dict, Optional

from .registry import Tool

_RESUMES_DIR = Path.home() / ".aura" / "resumes"

_TEMPLATE = """\
# {name}

{role}

---

## Contact
{contact}

---

## Skills
{skills}

---

## Experience
{experience}

---

## Education
{education}

---

## Summary
{summary}

---

*Generated by AURA — AI Unified Reasoning Architecture*
"""


def _parse_kv(args: str) -> Dict[str, str]:
    """Parse ``key="value" key2="value2"`` style arguments."""
    result: Dict[str, str] = {}
    # Use shlex to handle quoted values safely
    try:
        tokens = shlex.split(args)
    except ValueError:
        tokens = args.split()

    for token in tokens:
        if "=" in token:
            k, _, v = token.partition("=")
            result[k.strip().lower()] = v.strip().strip('"').strip("'")
    return result


class ResumeTool(Tool):
    """Generate a professional Markdown resume from key=value fields."""

    name = "resume_builder"
    description = (
        "Generate a professional resume.  "
        "Usage: /tool resume_builder create name=\"Your Name\" role=\"Job Title\" "
        "skills=\"skill1,skill2\" experience=\"...\" education=\"...\" "
        "email=\"...\" [summary=\"...\"]"
    )

    def run(self, args: str) -> str:
        parts = args.strip().split(None, 1)
        if not parts or parts[0].lower() in ("help", ""):
            return self._help()

        subcmd = parts[0].lower()
        rest = parts[1] if len(parts) > 1 else ""

        if subcmd == "create":
            return self._create(rest)

        if subcmd == "list":
            return self._list()

        if subcmd == "show":
            return self._show(rest.strip())

        return self._help()

    # ── private ────────────────────────────────────────────────────────────────

    def _create(self, args: str) -> str:
        kv = _parse_kv(args)

        name = kv.get("name", "Your Name")
        role = kv.get("role", kv.get("title", "Professional"))
        email = kv.get("email", "")
        phone = kv.get("phone", "")
        location = kv.get("location", "")
        linkedin = kv.get("linkedin", "")
        github = kv.get("github", "")
        skills_raw = kv.get("skills", "")
        experience = kv.get("experience", "")
        education = kv.get("education", "")
        summary = kv.get("summary", "")

        # Build contact section
        contact_parts = []
        if email:
            contact_parts.append(f"📧 {email}")
        if phone:
            contact_parts.append(f"📱 {phone}")
        if location:
            contact_parts.append(f"📍 {location}")
        if linkedin:
            contact_parts.append(f"🔗 LinkedIn: {linkedin}")
        if github:
            contact_parts.append(f"💻 GitHub: {github}")
        contact = "  \n".join(contact_parts) if contact_parts else "*(add contact info)*"

        # Format skills as bullet list
        if skills_raw:
            skill_list = [s.strip() for s in re.split(r"[,;]", skills_raw) if s.strip()]
            skills_section = "\n".join(f"- {s}" for s in skill_list)
        else:
            skills_section = "*(list your skills)*"

        # Format experience
        experience_section = experience if experience else "*(describe your work experience)*"

        # Format education
        education_section = education if education else "*(describe your education)*"

        # Summary
        summary_section = summary if summary else (
            f"Experienced {role} with a passion for delivering quality results."
        )

        content = _TEMPLATE.format(
            name=name,
            role=role,
            contact=contact,
            skills=skills_section,
            experience=experience_section,
            education=education_section,
            summary=summary_section,
        )

        # Save to disk
        _RESUMES_DIR.mkdir(parents=True, exist_ok=True)
        safe_name = re.sub(r"[^\w\s-]", "", name).replace(" ", "_").lower()
        path = _RESUMES_DIR / f"{safe_name}_resume.md"
        path.write_text(content, encoding="utf-8")

        return (
            f"📄 **Resume generated for {name}!**\n\n"
            f"Saved to: `{path}`\n\n"
            "---\n\n"
            f"{content}"
        )

    def _list(self) -> str:
        _RESUMES_DIR.mkdir(parents=True, exist_ok=True)
        files = sorted(_RESUMES_DIR.glob("*.md"))
        if not files:
            return "📂 No resumes saved yet.  Use `/tool resume_builder create ...` to generate one."
        lines = ["📂 Saved resumes:"]
        for f in files:
            lines.append(f"  • {f.name}")
        return "\n".join(lines)

    def _show(self, filename: str) -> str:
        if not filename:
            return "⚠️  Usage: /tool resume_builder show <filename>"
        _RESUMES_DIR.mkdir(parents=True, exist_ok=True)
        path = _RESUMES_DIR / filename
        if not path.exists():
            path = _RESUMES_DIR / f"{filename}.md"
        if not path.exists():
            return f"⚠️  Resume '{filename}' not found.  Use 'list' to see available resumes."
        return path.read_text(encoding="utf-8")

    @staticmethod
    def _help() -> str:
        return (
            "📄 **Resume Builder** — generate professional resumes.\n\n"
            "  **Create a resume:**\n"
            "  ```\n"
            "  /tool resume_builder create name=\"Jane Smith\" role=\"Software Engineer\" \\\n"
            "    skills=\"Python,Go,Docker\" experience=\"5 years at Acme Corp\" \\\n"
            "    education=\"BSc CS, MIT\" email=\"jane@example.com\"\n"
            "  ```\n\n"
            "  **List saved resumes:**\n"
            "  `/tool resume_builder list`\n\n"
            "  **Show a saved resume:**\n"
            "  `/tool resume_builder show jane_smith_resume`"
        )
