"""aura/workflows/app_scaffold.py — Scaffold a new Android app project.

This workflow creates a minimal Gradle-based Android project structure that
can immediately be opened in Android Studio or built with `./gradlew assembleDebug`.

Usage (in chat)
---------------
    /workflow app_scaffold MyApp com.example.myapp /path/to/output

What it creates
---------------
    <output_dir>/
    ├── settings.gradle
    ├── build.gradle           (root)
    ├── gradlew                (stub — real file generated by gradle wrapper)
    ├── gradle/
    │   └── wrapper/
    │       └── gradle-wrapper.properties
    └── app/
        ├── build.gradle
        └── src/main/
            ├── AndroidManifest.xml
            └── java/com/example/myapp/
                └── MainActivity.java

Note: This scaffold does NOT include a full Gradle wrapper binary.
Use `gradle wrapper` inside the project to generate the real `gradlew` script.
"""

from __future__ import annotations

import os
import stat
from pathlib import Path
from textwrap import dedent

from .base import Workflow


class AppScaffoldWorkflow(Workflow):
    """Scaffold a minimal Android app project from scratch."""

    name = "app_scaffold"
    description = (
        "Scaffold an Android project. "
        "Usage: /workflow app_scaffold <AppName> <package> <output_dir>"
    )

    def run(self, args: str) -> str:
        parts = args.strip().split()
        if len(parts) < 3:
            return (
                "[app_scaffold] Usage: /workflow app_scaffold "
                "<AppName> <package.name> <output_dir>"
            )

        app_name, package, output_dir_str = parts[0], parts[1], parts[2]
        output_dir = Path(output_dir_str).expanduser().resolve()

        log: list[str] = [f"[app_scaffold] Scaffolding '{app_name}' ({package}) → {output_dir}"]

        try:
            self._create_structure(app_name, package, output_dir)
        except Exception as exc:  # noqa: BLE001
            return f"[app_scaffold] Failed: {exc}"

        log.append("[app_scaffold] Done!  Next steps:")
        log.append(f"  1. cd {output_dir}")
        log.append("  2. gradle wrapper   (generates the real gradlew binary)")
        log.append("  3. ./gradlew assembleDebug")
        return "\n".join(log)

    # ── private ────────────────────────────────────────────────────────────────

    def _create_structure(self, app_name: str, package: str, root: Path) -> None:
        pkg_path = package.replace(".", "/")

        files: dict[str, str] = {
            "settings.gradle": dedent(f"""\
                rootProject.name = '{app_name}'
                include ':app'
            """),

            "build.gradle": dedent("""\
                // Root build.gradle
                buildscript {
                    repositories { google(); mavenCentral() }
                    dependencies {
                        classpath 'com.android.tools.build:gradle:8.1.0'
                    }
                }
                allprojects {
                    repositories { google(); mavenCentral() }
                }
            """),

            "gradle/wrapper/gradle-wrapper.properties": dedent("""\
                distributionBase=GRADLE_USER_HOME
                distributionPath=wrapper/dists
                distributionUrl=https\\://services.gradle.org/distributions/gradle-8.3-bin.zip
                zipStoreBase=GRADLE_USER_HOME
                zipStorePath=wrapper/dists
            """),

            # Stub gradlew shell script (real one requires the JAR from `gradle wrapper`)
            "gradlew": dedent("""\
                #!/usr/bin/env sh
                # Stub gradlew — run `gradle wrapper` to generate the real one.
                exec gradle "$@"
            """),

            "app/build.gradle": dedent(f"""\
                plugins {{
                    id 'com.android.application'
                }}
                android {{
                    compileSdk 34
                    defaultConfig {{
                        applicationId '{package}'
                        minSdk 24
                        targetSdk 34
                        versionCode 1
                        versionName '1.0'
                    }}
                    buildTypes {{
                        release {{
                            minifyEnabled false
                        }}
                    }}
                }}
                dependencies {{
                    implementation 'androidx.appcompat:appcompat:1.6.1'
                }}
            """),

            f"app/src/main/res/layout/activity_main.xml": dedent(f"""\
                <?xml version="1.0" encoding="utf-8"?>
                <!-- Layout for MainActivity — generated by AURA app_scaffold -->
                <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:gravity="center"
                    android:orientation="vertical">

                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:text="Welcome to {app_name}!" />

                </LinearLayout>
            """),

            f"app/src/main/java/{pkg_path}/MainActivity.java": dedent(f"""\
                package {package};

                import androidx.appcompat.app.AppCompatActivity;
                import android.os.Bundle;

                /**
                 * Main entry-point activity for {app_name}.
                 * Generated by AURA app_scaffold workflow.
                 */
                public class MainActivity extends AppCompatActivity {{
                    @Override
                    protected void onCreate(Bundle savedInstanceState) {{
                        super.onCreate(savedInstanceState);
                        setContentView(R.layout.activity_main);
                    }}
                }}
            """),

            "app/src/main/AndroidManifest.xml": dedent(f"""\
                <?xml version="1.0" encoding="utf-8"?>
                <manifest xmlns:android="http://schemas.android.com/apk/res/android"
                    package="{package}">

                    <application
                        android:label="{app_name}"
                        android:theme="@style/Theme.AppCompat">
                        <activity android:name=".MainActivity"
                            android:exported="true">
                            <intent-filter>
                                <action android:name="android.intent.action.MAIN" />
                                <category android:name="android.intent.category.LAUNCHER" />
                            </intent-filter>
                        </activity>
                    </application>
                </manifest>
            """),
        }

        for rel_path, content in files.items():
            full_path = root / rel_path
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(content, encoding="utf-8")

        # Make gradlew executable
        gradlew_path = root / "gradlew"
        gradlew_path.chmod(gradlew_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP)
