"""aura/ui/gui/webui.py — Full web chat interface for AURA.

Serves a complete, responsive, single-page chat application directly from
the AURA API server.  The UI is a self-contained HTML file with embedded
CSS and JavaScript — zero build step, zero npm, zero external CDN required.

Features
--------
  - Modern chat bubble interface with typing indicators
  - Dark / light theme toggle
  - Video call, voice call, and screen share buttons (WebRTC-ready stubs)
  - Pre-fab template selector sidebar
  - Responsive design (mobile, tablet, desktop)
  - PWA-installable (service worker + manifest)
  - APK download link integration
  - Keyboard shortcuts (Enter to send, Shift+Enter for newline)
  - Friendly animated AURA avatar
"""

from __future__ import annotations

# The HTML is generated by the ``render_chat_html`` function below.
# It is intentionally a single self-contained string so it can be served
# from memory without touching the filesystem.


def render_chat_html(api_base: str = "") -> str:
    """Return the complete HTML/CSS/JS for the AURA chat interface.

    Parameters
    ----------
    api_base:
        The base URL for API calls (e.g. "http://localhost:8000").
        If empty, the browser will use relative URLs.
    """
    return _CHAT_HTML.replace("{{API_BASE}}", api_base)


_CHAT_HTML = r"""<!DOCTYPE html>
<html lang="en" data-theme="dark">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>AURA — AI Unified Reasoning Architecture</title>
<meta name="description" content="AURA: Free AI assistant for everyone. Chat, voice, video, and real-world tools.">
<meta name="theme-color" content="#0a0e27">
<link rel="manifest" href="/manifest.json">
<style>
/* ═══════════════════════════════════════════════════════════════════════════
   AURA Chat Interface — CSS
   ═══════════════════════════════════════════════════════════════════════════ */

:root {
  /* Dark theme (default) */
  --bg-primary: #0a0e27;
  --bg-secondary: #111638;
  --bg-chat: #0d1130;
  --bg-input: #1a1f4e;
  --bg-user-bubble: #3b5bdb;
  --bg-aura-bubble: #1a1f4e;
  --text-primary: #e8eaff;
  --text-secondary: #8b8fba;
  --text-user: #ffffff;
  --text-aura: #e8eaff;
  --accent: #5c7cfa;
  --accent-glow: rgba(92, 124, 250, 0.3);
  --border: #252a5e;
  --success: #51cf66;
  --warning: #ffd43b;
  --danger: #ff6b6b;
  --shadow: 0 4px 24px rgba(0,0,0,0.3);
  --radius: 16px;
  --radius-sm: 8px;
  --transition: 0.3s cubic-bezier(0.4, 0, 0.2, 1);
}

[data-theme="light"] {
  --bg-primary: #f0f2ff;
  --bg-secondary: #ffffff;
  --bg-chat: #f5f6ff;
  --bg-input: #e8eaff;
  --bg-user-bubble: #3b5bdb;
  --bg-aura-bubble: #ffffff;
  --text-primary: #1a1c3d;
  --text-secondary: #5c5f8a;
  --text-user: #ffffff;
  --text-aura: #1a1c3d;
  --accent: #3b5bdb;
  --accent-glow: rgba(59, 91, 219, 0.2);
  --border: #d0d3e8;
  --shadow: 0 4px 24px rgba(0,0,0,0.08);
}

* { margin: 0; padding: 0; box-sizing: border-box; }

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
  background: var(--bg-primary);
  color: var(--text-primary);
  height: 100vh;
  overflow: hidden;
  transition: background var(--transition), color var(--transition);
}

/* ── Layout ─────────────────────────────────────────────────────────────── */

.app-container {
  display: flex;
  height: 100vh;
  width: 100vw;
}

/* ── Sidebar ────────────────────────────────────────────────────────────── */

.sidebar {
  width: 280px;
  background: var(--bg-secondary);
  border-right: 1px solid var(--border);
  display: flex;
  flex-direction: column;
  transition: transform var(--transition), background var(--transition);
  z-index: 100;
  overflow-y: auto;
}

.sidebar-header {
  padding: 20px;
  border-bottom: 1px solid var(--border);
  display: flex;
  align-items: center;
  gap: 12px;
}

.aura-logo {
  width: 44px;
  height: 44px;
  border-radius: 50%;
  background: linear-gradient(135deg, var(--accent), #845ef7);
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 20px;
  animation: pulse-glow 3s ease-in-out infinite;
  flex-shrink: 0;
}

@keyframes pulse-glow {
  0%, 100% { box-shadow: 0 0 12px var(--accent-glow); }
  50% { box-shadow: 0 0 24px var(--accent-glow), 0 0 48px rgba(132, 94, 247, 0.15); }
}

.aura-title { font-weight: 700; font-size: 18px; }
.aura-subtitle { font-size: 11px; color: var(--text-secondary); }

/* ── Template Cards ─────────────────────────────────────────────────────── */

.sidebar-section { padding: 16px 20px 8px; }
.sidebar-section-title {
  font-size: 11px;
  text-transform: uppercase;
  letter-spacing: 1.5px;
  color: var(--text-secondary);
  margin-bottom: 8px;
}

.template-card {
  padding: 10px 14px;
  margin: 4px 12px;
  border-radius: var(--radius-sm);
  cursor: pointer;
  transition: background var(--transition);
  display: flex;
  align-items: center;
  gap: 10px;
  border: 1px solid transparent;
}

.template-card:hover {
  background: var(--bg-input);
  border-color: var(--border);
}

.template-card.active {
  background: var(--accent);
  color: #fff;
  border-color: var(--accent);
}

.template-icon { font-size: 18px; flex-shrink: 0; }
.template-name { font-size: 13px; font-weight: 500; }

/* ── Sidebar Footer ─────────────────────────────────────────────────────── */

.sidebar-footer {
  margin-top: auto;
  padding: 16px 20px;
  border-top: 1px solid var(--border);
}

.sidebar-btn {
  width: 100%;
  padding: 8px 12px;
  margin: 4px 0;
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  background: transparent;
  color: var(--text-primary);
  cursor: pointer;
  font-size: 13px;
  text-align: left;
  transition: background var(--transition);
  display: flex;
  align-items: center;
  gap: 8px;
}
.sidebar-btn:hover { background: var(--bg-input); }

/* ── Main Chat Area ─────────────────────────────────────────────────────── */

.main-area {
  flex: 1;
  display: flex;
  flex-direction: column;
  min-width: 0;
}

/* ── Top Bar ────────────────────────────────────────────────────────────── */

.top-bar {
  height: 60px;
  background: var(--bg-secondary);
  border-bottom: 1px solid var(--border);
  display: flex;
  align-items: center;
  padding: 0 20px;
  gap: 12px;
  flex-shrink: 0;
}

.menu-toggle {
  display: none;
  background: none;
  border: none;
  color: var(--text-primary);
  font-size: 22px;
  cursor: pointer;
  padding: 4px;
}

.top-bar-title {
  font-weight: 600;
  font-size: 15px;
  flex: 1;
}

.status-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: var(--success);
  animation: status-blink 2s ease-in-out infinite;
}

@keyframes status-blink {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.4; }
}

.comm-buttons { display: flex; gap: 8px; }

.comm-btn {
  width: 36px;
  height: 36px;
  border-radius: 50%;
  border: 1px solid var(--border);
  background: var(--bg-input);
  color: var(--text-primary);
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 16px;
  transition: all var(--transition);
}
.comm-btn:hover {
  background: var(--accent);
  color: #fff;
  border-color: var(--accent);
  transform: scale(1.1);
}
.comm-btn.active {
  background: var(--danger);
  border-color: var(--danger);
  color: #fff;
}

.theme-toggle {
  background: none;
  border: 1px solid var(--border);
  color: var(--text-primary);
  width: 36px;
  height: 36px;
  border-radius: 50%;
  cursor: pointer;
  font-size: 16px;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all var(--transition);
}
.theme-toggle:hover { background: var(--bg-input); }

/* ── Messages Area ──────────────────────────────────────────────────────── */

.messages-area {
  flex: 1;
  overflow-y: auto;
  padding: 20px;
  display: flex;
  flex-direction: column;
  gap: 16px;
  scroll-behavior: smooth;
}

.message {
  display: flex;
  gap: 10px;
  max-width: 75%;
  animation: msg-slide-in 0.3s ease-out;
}

@keyframes msg-slide-in {
  from { opacity: 0; transform: translateY(12px); }
  to { opacity: 1; transform: translateY(0); }
}

.message.user { margin-left: auto; flex-direction: row-reverse; }

.message-avatar {
  width: 32px;
  height: 32px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 14px;
  flex-shrink: 0;
  margin-top: 4px;
}

.message.aura .message-avatar {
  background: linear-gradient(135deg, var(--accent), #845ef7);
}

.message.user .message-avatar {
  background: var(--bg-user-bubble);
}

.message-bubble {
  padding: 12px 16px;
  border-radius: var(--radius);
  line-height: 1.5;
  font-size: 14px;
  word-wrap: break-word;
  overflow-wrap: break-word;
}

.message.aura .message-bubble {
  background: var(--bg-aura-bubble);
  color: var(--text-aura);
  border-bottom-left-radius: 4px;
  border: 1px solid var(--border);
}

.message.user .message-bubble {
  background: var(--bg-user-bubble);
  color: var(--text-user);
  border-bottom-right-radius: 4px;
}

.message-time {
  font-size: 10px;
  color: var(--text-secondary);
  margin-top: 4px;
  padding: 0 4px;
}
.message.user .message-time { text-align: right; }

/* ── Typing Indicator ───────────────────────────────────────────────────── */

.typing-indicator {
  display: none;
  gap: 10px;
  max-width: 75%;
  padding: 0 0 4px 0;
}

.typing-indicator.visible { display: flex; }

.typing-dots {
  display: flex;
  gap: 4px;
  padding: 14px 18px;
  background: var(--bg-aura-bubble);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  border-bottom-left-radius: 4px;
}

.typing-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: var(--text-secondary);
  animation: typing-bounce 1.4s ease-in-out infinite;
}

.typing-dot:nth-child(2) { animation-delay: 0.2s; }
.typing-dot:nth-child(3) { animation-delay: 0.4s; }

@keyframes typing-bounce {
  0%, 60%, 100% { transform: translateY(0); opacity: 0.4; }
  30% { transform: translateY(-6px); opacity: 1; }
}

/* ── Input Area ─────────────────────────────────────────────────────────── */

.input-area {
  padding: 16px 20px;
  background: var(--bg-secondary);
  border-top: 1px solid var(--border);
  flex-shrink: 0;
}

.input-container {
  display: flex;
  align-items: flex-end;
  gap: 10px;
  max-width: 800px;
  margin: 0 auto;
}

.input-wrapper {
  flex: 1;
  background: var(--bg-input);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  display: flex;
  align-items: flex-end;
  padding: 4px;
  transition: border-color var(--transition);
}

.input-wrapper:focus-within {
  border-color: var(--accent);
  box-shadow: 0 0 0 3px var(--accent-glow);
}

#message-input {
  flex: 1;
  background: transparent;
  border: none;
  color: var(--text-primary);
  font-size: 14px;
  padding: 10px 12px;
  resize: none;
  min-height: 44px;
  max-height: 120px;
  line-height: 1.5;
  font-family: inherit;
  outline: none;
}

#message-input::placeholder { color: var(--text-secondary); }

.send-btn {
  width: 44px;
  height: 44px;
  border-radius: 50%;
  border: none;
  background: var(--accent);
  color: #fff;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 18px;
  transition: all var(--transition);
  flex-shrink: 0;
}

.send-btn:hover { transform: scale(1.08); background: #4c6ef5; }
.send-btn:disabled { opacity: 0.4; cursor: not-allowed; transform: none; }

.input-hint {
  text-align: center;
  font-size: 11px;
  color: var(--text-secondary);
  margin-top: 8px;
}

/* ── Welcome Screen ─────────────────────────────────────────────────────── */

.welcome-screen {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  text-align: center;
  padding: 40px 20px;
  gap: 24px;
}

.welcome-logo {
  width: 80px;
  height: 80px;
  border-radius: 50%;
  background: linear-gradient(135deg, var(--accent), #845ef7);
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 36px;
  animation: pulse-glow 3s ease-in-out infinite;
}

.welcome-title {
  font-size: 28px;
  font-weight: 700;
  background: linear-gradient(135deg, var(--accent), #845ef7);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.welcome-subtitle {
  font-size: 15px;
  color: var(--text-secondary);
  max-width: 480px;
  line-height: 1.6;
}

.quick-actions {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 12px;
  max-width: 640px;
  width: 100%;
  margin-top: 8px;
}

.quick-action {
  padding: 16px;
  background: var(--bg-secondary);
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  cursor: pointer;
  text-align: left;
  transition: all var(--transition);
  color: var(--text-primary);
}
.quick-action:hover {
  border-color: var(--accent);
  transform: translateY(-2px);
  box-shadow: var(--shadow);
}
.quick-action-icon { font-size: 24px; margin-bottom: 8px; }
.quick-action-title { font-weight: 600; font-size: 14px; margin-bottom: 4px; }
.quick-action-desc { font-size: 12px; color: var(--text-secondary); }

/* ── Communication Modal ────────────────────────────────────────────────── */

.modal-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0,0,0,0.6);
  display: none;
  align-items: center;
  justify-content: center;
  z-index: 200;
  animation: fade-in 0.2s ease-out;
}

.modal-overlay.visible { display: flex; }

@keyframes fade-in {
  from { opacity: 0; }
  to { opacity: 1; }
}

.modal {
  background: var(--bg-secondary);
  border-radius: var(--radius);
  border: 1px solid var(--border);
  padding: 32px;
  max-width: 480px;
  width: 90%;
  text-align: center;
  box-shadow: var(--shadow);
}

.modal-icon { font-size: 48px; margin-bottom: 16px; }
.modal-title { font-size: 20px; font-weight: 700; margin-bottom: 8px; }
.modal-desc { font-size: 14px; color: var(--text-secondary); margin-bottom: 24px; line-height: 1.5; }

.modal-btn {
  padding: 10px 24px;
  border-radius: var(--radius-sm);
  border: 1px solid var(--border);
  background: var(--bg-input);
  color: var(--text-primary);
  cursor: pointer;
  font-size: 14px;
  transition: all var(--transition);
  margin: 4px;
}
.modal-btn:hover { background: var(--accent); color: #fff; border-color: var(--accent); }
.modal-btn.primary { background: var(--accent); color: #fff; border-color: var(--accent); }
.modal-btn.primary:hover { background: #4c6ef5; }
.modal-btn.danger { background: var(--danger); color: #fff; border-color: var(--danger); }

/* ── Responsive ─────────────────────────────────────────────────────────── */

@media (max-width: 768px) {
  .sidebar {
    position: fixed;
    left: 0;
    top: 0;
    bottom: 0;
    transform: translateX(-100%);
  }
  .sidebar.open { transform: translateX(0); }
  .menu-toggle { display: block; }
  .message { max-width: 90%; }
  .quick-actions { grid-template-columns: 1fr; }
}

@media (max-width: 480px) {
  .top-bar { padding: 0 12px; }
  .messages-area { padding: 12px; }
  .input-area { padding: 12px; }
  .comm-buttons { gap: 4px; }
}

/* ── Scrollbar ──────────────────────────────────────────────────────────── */

::-webkit-scrollbar { width: 6px; }
::-webkit-scrollbar-track { background: transparent; }
::-webkit-scrollbar-thumb { background: var(--border); border-radius: 3px; }
::-webkit-scrollbar-thumb:hover { background: var(--text-secondary); }

/* ── Markdown in messages ───────────────────────────────────────────────── */

.message-bubble p { margin: 0 0 8px 0; }
.message-bubble p:last-child { margin-bottom: 0; }
.message-bubble strong { font-weight: 700; }
.message-bubble em { font-style: italic; }
.message-bubble code {
  background: rgba(0,0,0,0.2);
  padding: 2px 6px;
  border-radius: 4px;
  font-size: 13px;
  font-family: 'SF Mono', 'Fira Code', monospace;
}
.message-bubble pre {
  background: rgba(0,0,0,0.3);
  padding: 12px;
  border-radius: var(--radius-sm);
  overflow-x: auto;
  margin: 8px 0;
}
.message-bubble pre code { background: none; padding: 0; }
.message-bubble ul, .message-bubble ol { padding-left: 20px; margin: 8px 0; }
.message-bubble li { margin: 4px 0; }
</style>
</head>
<body>

<div class="app-container">
  <!-- ── Sidebar ──────────────────────────────────────────────────────── -->
  <aside class="sidebar" id="sidebar">
    <div class="sidebar-header">
      <div class="aura-logo">✦</div>
      <div>
        <div class="aura-title">AURA</div>
        <div class="aura-subtitle">AI Unified Reasoning Architecture</div>
      </div>
    </div>

    <div class="sidebar-section">
      <div class="sidebar-section-title">Quick Templates</div>
    </div>
    <div id="template-list">
      <!-- Populated by JS -->
    </div>

    <div class="sidebar-footer">
      <button class="sidebar-btn" onclick="resetTemplate()">🔄 Reset to Default</button>
      <button class="sidebar-btn" onclick="newChat()">✨ New Chat</button>
      <button class="sidebar-btn" id="install-btn" style="display:none" onclick="installApp()">📲 Install App</button>
      <div style="margin-top:12px;font-size:11px;color:var(--text-secondary)">
        Free &amp; open-source — by Christopher Betts
      </div>
    </div>
  </aside>

  <!-- ── Main ─────────────────────────────────────────────────────────── -->
  <main class="main-area">
    <!-- Top bar -->
    <div class="top-bar">
      <button class="menu-toggle" onclick="toggleSidebar()">☰</button>
      <div class="status-dot"></div>
      <div class="top-bar-title" id="top-title">AURA — Ready to help ✨</div>

      <div class="comm-buttons">
        <button class="comm-btn" id="btn-voice" onclick="toggleVoice()" title="Voice Call">🎤</button>
        <button class="comm-btn" id="btn-video" onclick="toggleVideo()" title="Video Call">📹</button>
        <button class="comm-btn" id="btn-screen" onclick="toggleScreen()" title="Screen Share">🖥️</button>
      </div>

      <button class="theme-toggle" onclick="toggleTheme()" title="Toggle theme">🌓</button>
    </div>

    <!-- Welcome screen (shown when no messages) -->
    <div class="welcome-screen" id="welcome-screen">
      <div class="welcome-logo">✦</div>
      <div class="welcome-title">Welcome to AURA</div>
      <div class="welcome-subtitle">
        I'm your free AI assistant — here to help with coding, writing, math, planning,
        and anything else you need. Pick a template or just start chatting!
      </div>
      <div class="quick-actions">
        <div class="quick-action" onclick="quickAction('code_helper')">
          <div class="quick-action-icon">💻</div>
          <div class="quick-action-title">Code Helper</div>
          <div class="quick-action-desc">Write, debug, and improve code</div>
        </div>
        <div class="quick-action" onclick="quickAction('writing_assistant')">
          <div class="quick-action-icon">✍️</div>
          <div class="quick-action-title">Writing Assistant</div>
          <div class="quick-action-desc">Essays, emails, reports, stories</div>
        </div>
        <div class="quick-action" onclick="quickAction('study_buddy')">
          <div class="quick-action-icon">📚</div>
          <div class="quick-action-title">Study Buddy</div>
          <div class="quick-action-desc">Learn with quizzes and explanations</div>
        </div>
        <div class="quick-action" onclick="quickAction('daily_planner')">
          <div class="quick-action-icon">📅</div>
          <div class="quick-action-title">Daily Planner</div>
          <div class="quick-action-desc">Organize tasks and set goals</div>
        </div>
      </div>
    </div>

    <!-- Messages -->
    <div class="messages-area" id="messages-area" style="display:none">
      <!-- Typing indicator -->
      <div class="typing-indicator" id="typing-indicator">
        <div class="message-avatar" style="background:linear-gradient(135deg,var(--accent),#845ef7)">✦</div>
        <div class="typing-dots">
          <div class="typing-dot"></div>
          <div class="typing-dot"></div>
          <div class="typing-dot"></div>
        </div>
      </div>
    </div>

    <!-- Input -->
    <div class="input-area">
      <div class="input-container">
        <div class="input-wrapper">
          <textarea id="message-input" placeholder="Type your message... (Shift+Enter for new line)"
                    rows="1" autofocus></textarea>
        </div>
        <button class="send-btn" id="send-btn" onclick="sendMessage()" disabled>➤</button>
      </div>
      <div class="input-hint">
        AURA is free and open-source — <a href="https://github.com/Cbetts1/AI-MODEL-200B-" target="_blank"
        style="color:var(--accent);text-decoration:none">GitHub</a> •
        /tool list • /template list
      </div>
    </div>
  </main>
</div>

<!-- ── Communication Modal ──────────────────────────────────────────────── -->
<div class="modal-overlay" id="comm-modal">
  <div class="modal">
    <div class="modal-icon" id="modal-icon">🎤</div>
    <div class="modal-title" id="modal-title">Voice Call</div>
    <div class="modal-desc" id="modal-desc">
      Voice calling is coming soon! AURA will support real-time voice
      conversations using WebRTC.
    </div>
    <div>
      <button class="modal-btn primary" onclick="closeModal()">Got it!</button>
    </div>
  </div>
</div>

<script>
/* ═══════════════════════════════════════════════════════════════════════════
   AURA Chat Interface — JavaScript
   ═══════════════════════════════════════════════════════════════════════════ */

const API_BASE = "{{API_BASE}}";
let sessionId = null;
let templates = [];
let activeTemplate = null;

// ── Startup ────────────────────────────────────────────────────────────────

document.addEventListener("DOMContentLoaded", () => {
  loadTemplates();
  setupInput();
  registerServiceWorker();
});

// ── Templates ──────────────────────────────────────────────────────────────

async function loadTemplates() {
  try {
    const resp = await fetch(API_BASE + "/v1/templates");
    const data = await resp.json();
    templates = data.templates || [];
    renderTemplateList();
  } catch (e) {
    console.warn("Could not load templates:", e);
  }
}

function renderTemplateList() {
  const container = document.getElementById("template-list");
  container.innerHTML = "";
  templates.forEach(t => {
    const card = document.createElement("div");
    card.className = "template-card" + (activeTemplate === t.name ? " active" : "");
    card.innerHTML = `<span class="template-icon">${t.icon}</span><span class="template-name">${t.title}</span>`;
    card.onclick = () => quickAction(t.name);
    container.appendChild(card);
  });
}

async function quickAction(templateName) {
  activeTemplate = templateName;
  renderTemplateList();
  showChatArea();
  showTyping();
  try {
    const resp = await fetch(API_BASE + "/v1/template", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ template: templateName })
    });
    const data = await resp.json();
    sessionId = data.session_id || sessionId;
    hideTyping();
    addMessage("aura", data.reply || data.greeting || `Template '${templateName}' activated!`);
    const tpl = templates.find(t => t.name === templateName);
    if (tpl) {
      document.getElementById("top-title").textContent = tpl.icon + " " + tpl.title + " — AURA";
    }
  } catch (e) {
    hideTyping();
    addMessage("aura", `✨ ${templateName.replace(/_/g, " ")} mode activated! How can I help?`);
  }
  closeSidebar();
}

function resetTemplate() {
  activeTemplate = null;
  renderTemplateList();
  document.getElementById("top-title").textContent = "AURA — Ready to help ✨";
  sendChatMessage("/template reset");
}

function newChat() {
  activeTemplate = null;
  renderTemplateList();
  sessionId = null;
  document.getElementById("messages-area").innerHTML = createTypingIndicator();
  document.getElementById("messages-area").style.display = "none";
  document.getElementById("welcome-screen").style.display = "flex";
  document.getElementById("top-title").textContent = "AURA — Ready to help ✨";
  closeSidebar();
}

// ── Messaging ──────────────────────────────────────────────────────────────

function setupInput() {
  const input = document.getElementById("message-input");
  const sendBtn = document.getElementById("send-btn");

  input.addEventListener("input", () => {
    input.style.height = "auto";
    input.style.height = Math.min(input.scrollHeight, 120) + "px";
    sendBtn.disabled = !input.value.trim();
  });

  input.addEventListener("keydown", (e) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      if (input.value.trim()) sendMessage();
    }
  });
}

async function sendMessage() {
  const input = document.getElementById("message-input");
  const text = input.value.trim();
  if (!text) return;

  input.value = "";
  input.style.height = "auto";
  document.getElementById("send-btn").disabled = true;

  showChatArea();
  addMessage("user", text);
  await sendChatMessage(text);
}

async function sendChatMessage(text) {
  showTyping();
  try {
    const resp = await fetch(API_BASE + "/v1/chat", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ message: text, session_id: sessionId })
    });
    const data = await resp.json();
    sessionId = data.session_id || sessionId;
    hideTyping();
    addMessage("aura", data.reply);
  } catch (e) {
    hideTyping();
    addMessage("aura", "⚠️ Could not reach the AURA server. Make sure it's running with `aura serve`.");
  }
}

// ── UI Helpers ─────────────────────────────────────────────────────────────

function addMessage(role, text) {
  const area = document.getElementById("messages-area");
  const typing = document.getElementById("typing-indicator");

  const msgDiv = document.createElement("div");
  msgDiv.className = `message ${role}`;

  const avatar = role === "aura" ? "✦" : "👤";
  const time = new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });

  msgDiv.innerHTML = `
    <div class="message-avatar">${avatar}</div>
    <div>
      <div class="message-bubble">${formatMessage(text)}</div>
      <div class="message-time">${time}</div>
    </div>
  `;

  area.insertBefore(msgDiv, typing);
  area.scrollTop = area.scrollHeight;
}

function formatMessage(text) {
  if (!text) return "";
  // Basic markdown-ish formatting
  let html = text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/```([\s\S]*?)```/g, "<pre><code>$1</code></pre>")
    .replace(/`([^`]+)`/g, "<code>$1</code>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/\n/g, "<br>");
  return html;
}

function showChatArea() {
  document.getElementById("welcome-screen").style.display = "none";
  document.getElementById("messages-area").style.display = "flex";
}

function showTyping() {
  const t = document.getElementById("typing-indicator");
  if (t) t.classList.add("visible");
  const area = document.getElementById("messages-area");
  if (area) area.scrollTop = area.scrollHeight;
}

function hideTyping() {
  const t = document.getElementById("typing-indicator");
  if (t) t.classList.remove("visible");
}

function createTypingIndicator() {
  return `<div class="typing-indicator" id="typing-indicator">
    <div class="message-avatar" style="background:linear-gradient(135deg,var(--accent),#845ef7)">✦</div>
    <div class="typing-dots">
      <div class="typing-dot"></div>
      <div class="typing-dot"></div>
      <div class="typing-dot"></div>
    </div>
  </div>`;
}

// ── Theme ──────────────────────────────────────────────────────────────────

function toggleTheme() {
  const html = document.documentElement;
  const current = html.getAttribute("data-theme");
  const next = current === "dark" ? "light" : "dark";
  html.setAttribute("data-theme", next);
  localStorage.setItem("aura-theme", next);
}

// Restore theme
(function() {
  const saved = localStorage.getItem("aura-theme");
  if (saved) document.documentElement.setAttribute("data-theme", saved);
})();

// ── Sidebar ────────────────────────────────────────────────────────────────

function toggleSidebar() {
  document.getElementById("sidebar").classList.toggle("open");
}

function closeSidebar() {
  document.getElementById("sidebar").classList.remove("open");
}

// Close sidebar when clicking outside on mobile
document.addEventListener("click", (e) => {
  const sidebar = document.getElementById("sidebar");
  const toggle = document.querySelector(".menu-toggle");
  if (sidebar.classList.contains("open") &&
      !sidebar.contains(e.target) &&
      !toggle.contains(e.target)) {
    sidebar.classList.remove("open");
  }
});

// ── Communication Buttons ──────────────────────────────────────────────────

function toggleVoice() {
  showCommModal("🎤", "Voice Call",
    "Voice calling is coming soon! AURA will support real-time voice " +
    "conversations. The model runs remotely — your device just handles " +
    "audio streaming, keeping it lightweight and fast.");
}

function toggleVideo() {
  showCommModal("📹", "Video Call",
    "Video calling is in development! AURA will support face-to-face " +
    "video conversations with real-time AI assistance via WebRTC. " +
    "All processing happens on the server — zero burden on your device.");
}

function toggleScreen() {
  showCommModal("🖥️", "Screen Share",
    "Screen sharing is coming soon! Share your screen with AURA and get " +
    "real-time help with what you're working on. AURA can read your screen, " +
    "suggest edits, and guide you step by step.");
}

function showCommModal(icon, title, desc) {
  document.getElementById("modal-icon").textContent = icon;
  document.getElementById("modal-title").textContent = title;
  document.getElementById("modal-desc").textContent = desc;
  document.getElementById("comm-modal").classList.add("visible");
}

function closeModal() {
  document.getElementById("comm-modal").classList.remove("visible");
}

// ── PWA / Install ──────────────────────────────────────────────────────────

let deferredPrompt = null;

window.addEventListener("beforeinstallprompt", (e) => {
  e.preventDefault();
  deferredPrompt = e;
  document.getElementById("install-btn").style.display = "block";
});

function installApp() {
  if (deferredPrompt) {
    deferredPrompt.prompt();
    deferredPrompt = null;
    document.getElementById("install-btn").style.display = "none";
  }
}

function registerServiceWorker() {
  if ("serviceWorker" in navigator) {
    navigator.serviceWorker.register("/sw.js").catch(() => {});
  }
}
</script>
</body>
</html>"""
